// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const browser: typeof import('wxt/browser').browser
  const colorAlgorithm: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').colorAlgorithm
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createMainChart: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').createMainChart
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const dayDate: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').dayDate
  const dayStats: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').dayStats
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const destroyPreviousChart: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').destroyPreviousChart
  const detailChart: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').detailChart
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const fillMissingDates: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/date').fillMissingDates
  const formatDate: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/utils').formatDate
  const formatKey: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/utils').formatKey
  const formatLabels: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/utils').formatLabels
  const formatValue: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/utils').formatValue
  const fullData: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/state').fullData
  const generateDateRange: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/date').generateDateRange
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const getCurrentStartDate: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/date').getCurrentStartDate
  const getDaysInMonth: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/date').getDaysInMonth
  const getDomain: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/utils').getDomain
  const getFromStorage: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/theme').getFromStorage
  const getIsDark: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/theme').getIsDark
  const getPreviousPeriodRange: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/date').getPreviousPeriodRange
  const getStartDate: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/date').getStartDate
  const getTotal: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/utils').getTotal
  const getUiHue: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/theme').getUiHue
  const getValues: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/utils').getValues
  const getViewMode: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').getViewMode
  const getViewRange: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').getViewRange
  const handleChartClick: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').handleChartClick
  const initTheme: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/theme').initTheme
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const mainChart: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').mainChart
  const mainChartNav: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').mainChartNav
  const navigateChart: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/date').navigateChart
  const navigateStats: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').navigateStats
  const processAggregatedData: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/utils').processAggregatedData
  const renderMainChart: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').renderMainChart
  const setCurrentStartDate: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/date').setCurrentStartDate
  const settingsIcon: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').settingsIcon
  const storage: typeof import('wxt/utils/storage').storage
  const toLocalISODate: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/date').toLocalISODate
  const today: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/date').today
  const updateAverage: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').updateAverage
  const updateChart: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').updateChart
  const updateUI: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').updateUI
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const viewRange: typeof import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/ui').viewRange
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { RawData, FullData } from '/home/vlad/Desktop/dev/git-projects/time-flow/utils/types'
  import('/home/vlad/Desktop/dev/git-projects/time-flow/utils/types')
}
