// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/favicon/128.png"
    | "/favicon/16.png"
    | "/favicon/48.png"
    | "/main.html"
    | "/pause.svg"
    | "/popup.html"
    | "/resume.svg"
    | "/settings-icon.svg"
    | "/theme-icon.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
